apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod # Name of our pod
spec:
  restartPolicy: Never
  volumes:
  - name: shared-date-logs  # Creating a shared volume for my containers "container-writing-dates" and "container-serving-dates"
    emptyDir: {}            # On node where POD was assigned, this directory will be used for shared volume /var/lib/kubelet/<pod-uid>/volumes
  initContainers:
    - name: ubuntu-demo
      image: ubuntu
      command:
        - /bin/sh
        - "-c"
        - "echo Welcome to k8s initContainers"
    - name: alpine-demo
      image: alpine
      command:
        - /bin/sh
        - "-c"
        - "echo Welcome to k8s Alpine"
  containers:
  - name: container-writing-dates # Name of first container
    image: alpine # Image to use for first container
    command: ["/bin/sh"]
    args: ["-c", "while true; do ls -l /sumanpulluru; sleep 10;done"] # writing date command output to index.html file for every 10sec
    volumeMounts:
    - name: shared-date-logs
      mountPath: /var/log # Mounting log dir so app can write to it.
    resources:
      limits:
        cpu: "0.2"
        memory: "200Mi"
      requests:
        cpu: "0.1"
        memory: "100Mi"
  - name: container-serving-dates # Name of second container
    image: nginx:1.19.0 # Image for second container
    ports:
      - containerPort: 80 # Defining what port to use.
        hostPort: 8090
    volumeMounts:
    - name: shared-date-logs
      mountPath: /usr/share/nginx/html # Where nginx will serve the written file
    resources:
      limits:
        cpu: "0.4"
        memory: "400Mi"
      requests:
        cpu: "0.2"
        memory: "200Mi"